# Generated by Django 5.1.1 on 2024-10-10 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="majors",
        ),
        migrations.RemoveField(
            model_name="minor",
            name="required_courses",
        ),
        migrations.RemoveField(
            model_name="student",
            name="minors",
        ),
        migrations.RemoveField(
            model_name="department",
            name="code",
        ),
        migrations.CreateModel(
            name="Program",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("schools", models.TextField()),
                ("types", models.TextField()),
                ("url", models.URLField()),
                ("required_units", models.PositiveIntegerField(blank=True)),
                (
                    "required_courses",
                    models.ManyToManyField(blank=True, to="api.course"),
                ),
            ],
        ),
        migrations.AddField(
            model_name="student",
            name="programs",
            field=models.ManyToManyField(blank=True, to="api.program"),
        ),
        migrations.DeleteModel(
            name="Major",
        ),
        migrations.DeleteModel(
            name="Minor",
        ),
    ]
