# Generated by Django 5.1.1 on 2024-10-10 17:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_alter_course_prerequisites"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.RemoveField(
            model_name="course",
            name="prerequisites",
        ),
        migrations.AlterField(
            model_name="program",
            name="schools",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="program",
            name="types",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="course",
            name="prerequisites",
            field=models.TextField(blank=True),
        ),
    ]
