# Generated by Django 5.1.1 on 2024-10-10 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_alter_course_description_remove_course_prerequisites_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="career",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="student",
            name="interests",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="student",
            name="required_units",
            field=models.IntegerField(blank=True),
        ),
    ]
