# Generated by Django 5.1.1 on 2024-10-10 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_alter_course_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="program",
            name="required_courses",
            field=models.ManyToManyField(blank=True, to="api.course"),
        ),
    ]
