# Generated by Django 5.1.1 on 2024-10-10 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_alter_program_required_courses"),
    ]

    operations = [
        migrations.AddField(
            model_name="semester",
            name="planned_credits",
            field=models.PositiveIntegerField(default=15),
        ),
        migrations.AlterField(
            model_name="semester",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="semester",
            name="planned_courses",
            field=models.ManyToManyField(blank=True, to="api.course"),
        ),
    ]
