# Generated by Django 5.1.1 on 2024-10-10 18:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0009_semester_planned_credits_alter_semester_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="program",
            name="required_courses",
            field=models.ManyToManyField(blank=True, to="api.course"),
        ),
    ]
