# Generated by Django 5.1.1 on 2024-10-12 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_alter_student_options_alter_student_managers_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="semester",
            name="isCompleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="student",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name="student",
            name="grad",
            field=models.IntegerField(blank=True, default=2028),
        ),
        migrations.AlterField(
            model_name="student",
            name="joined",
            field=models.IntegerField(blank=True, default=2024),
        ),
        migrations.AlterField(
            model_name="student",
            name="password",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
        migrations.AlterField(
            model_name="student",
            name="username",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
