# Generated by Django 5.1.1 on 2024-10-12 04:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0012_alter_semester_iscompleted_alter_student_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="username",
            field=models.CharField(max_length=150, null=True),
        ),
    ]
