# Generated by Django 5.1.1 on 2024-10-12 04:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0013_alter_student_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="username",
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
