# Generated by Django 5.1.2 on 2024-10-25 22:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0014_alter_student_username"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="joined",
        ),
        migrations.AlterField(
            model_name="student",
            name="grad",
            field=models.IntegerField(),
        ),
    ]
