# Generated by Django 5.1.2 on 2024-10-25 22:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0015_remove_student_joined_alter_student_grad"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="grad",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
