# Generated by Django 5.1.2 on 2024-11-03 20:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0017_review"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="embedding",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="embedding",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
