# Generated by Django 5.1.3 on 2024-12-02 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0018_course_embedding_student_embedding"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="attributes",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="semester",
            name="planned_credits",
            field=models.PositiveIntegerField(default=12),
        ),
    ]
