version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: washu_course_scheduler_backend
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      - FRONTEND_ADDRESS=http://localhost:3000

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: washu_course_scheduler_frontend
    restart: always
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - VITE_APP_BACKEND_ADDRESS=http://localhost:8000
