version: "3.8"

services:
  backend-release:
    image: washu_course_scheduler_backend:release
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: washu_course_scheduler_backend_release
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=backend.settings

  frontend-release:
    image: washu_course_scheduler_frontend:release
    build:
      context: ./frontend
      dockerfile: Dockerfile.release
      args:
        - VITE_APP_BACKEND_ADDRESS=http://localhost:8000
    restart: always
    ports:
      - "3000:3000"
