repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
  - repo: https://github.com/hadialqattan/pycln
    rev: v2.1.3
    hooks:
      - id: pycln
        description: "A formatter for finding and removing unused import statements."
        args: [--config=backend/pyproject.toml]
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        description: "A utility to sort imports alphabetically, and automatically separated into sections and by type."
        args: ["--settings-path=backend/pyproject.toml"]
  - repo: https://github.com/psf/black
    rev: 23.9.1
    hooks:
      - id: black
        description: "A PEP8 compliant code formatter."
        language_version: python3.11
        args: ["--config=backend/pyproject.toml"]
  - repo: local
    hooks:
      - id: pylint
        description: "A static code analyzer."
        name: pylint
        entry: bash -c 'cd backend && poetry run pylint backend --disable=C0301'
        language: system
        types: [python]
        args:
          [
            "-rn", # Only display messages
            "-sn", # Don't display the score
          ]
      # - id: pyright
      #   description: "A static type checker."
      #   name: pyright
      #   entry: bash -c 'cd backend && poetry run pyright'
      #   language: system
      #   types: [python]
  # - repo: https://github.com/pycqa/pydocstyle
  #   rev: 6.3.0
  #   hooks:
  #     - id: pydocstyle
  #       description: "A static analysis tool for checking compliance with Python docstring conventions."
  #       args: [--config=backend/pyproject.toml]
  - repo: local
    hooks:
      - id: sync-poetry-lock
        name: Sync poetry.lock
        description: "A check that the poetry.lock has been synced with any changes in pyproject.toml."
        language: system
        entry: cd backend && poetry lock --no-update
        args: ["-C", "./backend"]
        files: ^backend/pyproject.toml$
        pass_filenames: false
