apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: washu_course_scheduler_frontend:release
        command: ["nginx", "-g", "daemon off;"]
        ports:
          - containerPort: 80
        env:
          - name: APP_APPLICATION__HOST
            value: 0.0.0.0

---

apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: ClusterIP
  selector:
    app: frontend
  ports:
    - port: 80
      targetPort: 80
