apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: washu_course_scheduler_frontend:release
          imagePullPolicy: Never
          command: ["nginx", "-g", "daemon off;"]
          ports:
            - containerPort: 3000
          env:
            - name: VITE_APP_BACKEND_ADDRESS
              value: /backend

---

apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: LoadBalancer
  selector:
    app: frontend
  ports:
    - port: 3000
      targetPort: 3000
