apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: washu-course-scheduler-ingress
spec:
  rules:
    - http:
        paths:
          ################
          # URL ROUTING #
          ################
          - pathType: Prefix
            path: /admin
            backend:
              service:
                name: backend-service
                port:
                  number: 8000
          - pathType: Prefix
            path: /auth
            backend:
              service:
                name: backend-service
                port:
                  number: 8000
          - pathType: Prefix
            path: /api
            backend:
              service:
                name: backend-service
                port:
                  number: 8000
          ##########################
          # STATIC FOLDER ROUTING #
          ##########################
          - pathType: Prefix
            path: /static/admin/
            backend:
              service:
                name: backend-service
                port:
                  number: 8000
          - pathType: Prefix
            path: /static/rest_framework/
            backend:
              service:
                name: backend-service
                port:
                  number: 8000
          ################
          # URL ROUTING #
          ################
          - pathType: Prefix
            path: /
            backend:
              service:
                name: frontend-service
                port:
                  number: 80