name: Backend CI

on:
  push:
    branches:
      - main
  pull_request:
    branches: ["*"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install Poetry
      run: |
        cd backend
        python -m pip install --upgrade pip
        pip install poetry

    - name: Install dependencies
      run: |
        cd backend
        poetry install

    - name: Seed Database
      run: |
        cd backend
        poetry run python manage.py seed_data

    - name: Run pre-commit checks
      run: |
        cd backend
        poetry run pre-commit run -a

    - name: Run tests
      run: |
        cd backend
        poetry run python3 manage.py test
